DROP TABLE IF EXISTS Proposals;
DROP TABLE IF EXISTS Admins;

CREATE TABLE Admins (
  username VARCHAR(50) NOT NULL PRIMARY KEY,
  password VARCHAR(50) NOT NULL
);

CREATE TABLE Proposals (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title VARCHAR(255),
	author VARCHAR(255),
	description VARCHAR(10000),
	validation INTEGER,
	nVotes INTEGER
);
